// Package migrations holds the PocketBase schema migrations.
//
// Files alongside this one are generated by migratecmd's Automigrate whenever
// the schema changes in the Admin UI. This file exists so the package is
// importable before the first migration is generated.
package migrations
